# Site settings
title:  "초짜 VL 석사생" 
header-img: img/about-bg.jpg
email: tjddus9597@dgist.ac.kr
copyright_name: tjddus9597/초짜 VL 석사생
description: "개발자를생 위한 개발자"
baseurl: ""
url: "http://tjddus9597.github.io"
github_username:  tjddus9597
facebook_username:  tjddus9597
email_username:  tjddus9597@dgist.ac.kr

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92346434-1

# Disqus comments
disqus_shortname: tjddus9597

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
